from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA_DIR = ROOT / "data" / "raw"
RESULTS_DIR = ROOT / "results"
MODELS_DIR = ROOT / "models"

RANDOM_SEED = 42
TEST_SIZE = 0.10
VALID_SIZE = 0.10

TFIDF_MAX_FEATURES = 100_000
TFIDF_NGRAM_RANGE = (1, 2)
TFIDF_MIN_DF = 2

TRANSFORMER_NAME = "distilbert-base-uncased"
MAX_LENGTH = 256
BATCH_SIZE = 16
LEARNING_RATE = 2e-5
WEIGHT_DECAY = 0.01
EPOCHS = 3
WARMUP_RATIO = 0.10
PATIENCE = 2
GRAD_CLIP_NORM = 1.0
